
services:
    mosquitto:
        image: eclipse-mosquitto:2
        container_name: mosquitto
        restart: always
        ports:
            - 1883:1883
            - 1884:1884
        volumes:
            #- mqtt_data:/mosquitto/config
            - config:/mosquitto/config
            - data:/mosquitto/data
            - log:/mosquitto/log
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge
volumes:
  config:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/docker/mosquitto/config
      o: bind
  data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/docker/mosquitto/data
      o: bind
  log:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/docker/mosquitto/log
      o: bind      