services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:  christoph 
      MYSQL_PASSWORD: diana1966
      MYSQL_DATABASE: test
      TZ: Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/docker/maria
      o: bind