services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/docker/jellyfin/config:/config
      - /home/docker/jellyfin/cache:/cache
      - type: bind
        source: /home/christoph/test
        target: /media
      - type: bind
        source: /home/christoph/usb
        target: /media2
        read_only: true
    restart: 'unless-stopped'